### ISSUE TITLE
Issue a warning upon impact

### ISSUE THREAD

**Issue by E3V3A** [mykle1/MMM-NEO#3]
Can you please provide a notification in case there is an impact? 
It would also be nice if the RPi would sync and shut down gracefully if there is such an impact. 
Thanks.

**Comment by mykle1** [comment]
This is not an issue. It's a feature request. :-)

**Comment by E3V3A** [comment]
You may also consider including the amazing [nocode](https://github.com/kelseyhightower/nocode/) library. It will help resolve all sort of known and unknown issues, including the one in OP.
